apiVersion: hive.openshift.io/v1alpha1
kind: SyncSet
metadata:
  name: mygroup
spec:
  clusterDeploymentRefs:
  - name: mycluster

  resourceApplyMode: Upsert

  resources:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: mycm
    data:
      sample: My sample test sync set.
